name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - alloc
          - heapless
          - std
          - alloc,derive
          - heapless,derive
          - std,derive

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
    - name: Test with a feature subset
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features ${{ matrix.features }} --verbose
